# Generated by Django 3.0.6 on 2020-05-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200516_1848'),
        ('jobs', '0003_auto_20200507_2242'),
    ]

    operations = [
    ]
